// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gosustream.lol.domain;

import com.gosustream.lol.domain.LiveGame;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LiveGame_Roo_Configurable {
    
    declare @type: LiveGame: @Configurable;
    
}
