// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gosustream.lol.domain;

import com.gosustream.lol.domain.Game;
import com.gosustream.lol.domain.GameDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GameDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GameDataOnDemand: @Component;
    
    private Random GameDataOnDemand.rnd = new SecureRandom();
    
    private List<Game> GameDataOnDemand.data;
    
    public Game GameDataOnDemand.getNewTransientGame(int index) {
        Game obj = new Game();
        setEndTime(obj, index);
        setGameId(obj, index);
        setPriority(obj, index);
        setStartTime(obj, index);
        setStreamId(obj, index);
        return obj;
    }
    
    public void GameDataOnDemand.setEndTime(Game obj, int index) {
        Date endTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndTime(endTime);
    }
    
    public void GameDataOnDemand.setGameId(Game obj, int index) {
        String gameId = "gameId_" + index;
        obj.setGameId(gameId);
    }
    
    public void GameDataOnDemand.setPriority(Game obj, int index) {
        int priority = index;
        obj.setPriority(priority);
    }
    
    public void GameDataOnDemand.setStartTime(Game obj, int index) {
        Date startTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartTime(startTime);
    }
    
    public void GameDataOnDemand.setStreamId(Game obj, int index) {
        String streamId = "streamId_" + index;
        obj.setStreamId(streamId);
    }
    
    public Game GameDataOnDemand.getSpecificGame(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Game obj = data.get(index);
        Long id = obj.getId();
        return Game.findGame(id);
    }
    
    public Game GameDataOnDemand.getRandomGame() {
        init();
        Game obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Game.findGame(id);
    }
    
    public boolean GameDataOnDemand.modifyGame(Game obj) {
        return false;
    }
    
    public void GameDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Game.findGameEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Game' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Game>();
        for (int i = 0; i < 10; i++) {
            Game obj = getNewTransientGame(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
